console.log('polina'+ false)
console.log('polinka'+ 8)
console.log(45+ false)
console.log(45+ true)

console.log('polina'* false)
console.log('polinka'* 4)
console.log(32*true)
console.log(32*false)

console.log('polina'/ true)
console.log('polinka'/ 3)
console.log(12/ true)
console.log(12/ false)

console.log(Number(`123`))
console.log(Number(true))
console.log(String(123))
console.log(String(true))
console.log(Boolean(1))
console.log(Boolean(``))
